const data={
    products:[
        {
            id:1,
            name:'Product-1',
            slug:'product-one',
            category:'CategoryOne',
            image:'/images/pack4.jpg',
            price:100,
            countInStock:8,
            brand:'brandone',
            rating:4.0,
            numReviews:12,
            description:'The Best Product 1',

        },
        {
            id:2,
            name:'Product-2',
            slug:'product-two',
            category:'CategoryTwo',
            image:'/images/shirle.jpg',
            price:150,
            countInStock:8,
            brand:'brandone',
            rating:4.5,
            numReviews:12,
            description:'The Best Product 2',

        },
        {
            id:3,
            name:'Product-3',
            slug:'product-three',
            category:'CategoryThree',
            image:'/images/pack6.jpg',
            price:300,
            countInStock:0,
            brand:'brandone',
            rating:4.6,
            numReviews:17,
            description:'The Best Product 3',

        },
        {
            id:4,
            name:'Product-4',
            slug:'product-four',
            category:'CategoryFour',
            image:'/images/pack3.jpg',
            price:500,
            countInStock:3,
            brand:'brandone',
            rating:4.6,
            numReviews:12,
            description:'The Best Product 4',

        },
        {
            id:5,
            name:'Product-5',
            slug:'product-five',
            category:'CategoryFive',
            image:'/images/jeans.webp',
            price:300,
            countInStock:10,
            brand:'brandone',
            rating:4.9,
            numReviews:10,
            description:'The Best Product 5',
        },
        {
            id:6,
            name:'Product-6',
            slug:'product-six',
            category:'CategorySix',
            image:'/images/pack7.jpg',
            price:600,
            countInStock:8,
            brand:'brandone',
            rating:4.4,
            numReviews:7,
            description:'The Best Product 6',
        },
        {
            id:7,
            name:'Product-7',
            slug:'product-seven',
            category:'CategorySeven',
            image:'/images/pack8.jpg',
            price:160,
            countInStock:8,
            brand:'brandone',
            rating:4.7,
            numReviews:11,
            description:'The Best Product 7',
        },
        {
            id:8,
            name:'Product-8',
            slug:'product-eight',
            category:'CategoryEight',
            image:'/images/pack9.jpeg',
            price:190,
            countInStock:8,
            brand:'brandone',
            rating:4.2,
            numReviews:10,
            description:'The Best Product 8',
        },
    ],
};
export default data;